export enum DisciplineType {
  MANDATORY = 'MANDATORY',
  OPTIONAL = 'OPTIONAL',
  FACULTATIVE = 'FACULTATIVE',
}

export enum AssessmentType {
  EXAM = 'EXAM',
  COLLOQUIUM = 'COLLOQUIUM',
  VERIFICATION = 'VERIFICATION',
}

export enum TeachingActivityType {
  COURSE = 'COURSE',
  SEMINAR = 'SEMINAR',
  LABORATORY = 'LABORATORY',
  PROJECT = 'PROJECT',
}

export enum EnrollmentPeriodType {
  ELECTIVE_DISCIPLINES = 'ELECTIVE DISCIPLINES',
  COMPLEMENTARY_DISCIPLINES = 'COMPLEMENTARY DISCIPLINES',
  THESIS_REGISTRATION = 'THESIS REGISTRATION'
}

export enum TeachingLanguage {
  EN = 'EN',
  RO = 'RO',
}

export enum LearningOutcomeCategory {
  KNOWLEDGE = 'KNOWLEDGE',
  SKILLS = 'SKILLS',
  RESPONSIBILITY_AND_AUTONOMY = 'RESPONSIBILITY_AND_AUTONOMY',
}

export enum EnrollmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  WAITLIST = 'WAITLIST',
}


